scrape_configs:
  - job_name: 'accounts_service_job'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Accounts_service'
